# Results

```{r}
library(tidyverse)
library(hms)
library(ggplot2)
library(lubridate)
library(scales)
library(tigris)
library(cartography)
library(sf)
options(tigris_use_cache = TRUE)
crash <- read_csv('Motor_Vehicle_Collisions_Crashes.csv')
names(crash) <- make.names(names(crash), unique=TRUE)
crash<-crash%>% drop_na(CRASH.TIME)
crash$CRASH.TIME <- as.hms(crash$CRASH.TIME)
crash<-crash[ order(crash$CRASH.TIME , decreasing = FALSE ),]
crash$CRASH.TIME.hr.range <- hour(crash$CRASH.TIME)
ggplot(crash,aes(x = CRASH.TIME.hr.range)) +
  geom_histogram(stat='count')+ 
  scale_x_continuous(breaks = seq(23, 0, -1), labels=c("23" = "23-24", "22" = "22-23", "21" = "21-22", "20" = "20-21", "19" = "19-20", "18" = "18-19", "17" = "17-18", "16" = "16-17", "15" = "15-16", "14" = "14-15", "13" = "13-14", "12" = "12-13", "11" = "11-12", "10" = "10-11", "9" = "9-10", "8" = "8-9", "7" = "7-8", "6" = "6-7", "5" = "5-6", "4" = "4-5", "3" = "3-4", "1" = "1-2","2" = "2-3", '0' = "0-1"))+
  coord_flip()+
  labs(
    title = "Crashes based on time",
    x = "Time in hours",
    y = "Number of crashes")
```


```{r}
crash$CRASH.DATE <- as.Date(crash$CRASH.DATE , format = "%m/%d/%Y")
monthly<-crash %>%
mutate(month = format(CRASH.DATE, "%m")) %>%
group_by(month) %>%
count()
monthly$month=seq(1,12,1)
monthly$month <- as.Date(paste0("2018-", monthly$month, "-1"))
ggplot(monthly, aes(x=month, y=n)) +
  geom_line() + 
  xlab("")+scale_x_date(labels = date_format("%b"))+
  labs(
    title = "Crashes based on Month",
    x = "Days",
    y = "Number of crashes")

#Get highest month
```


```{r}
daily<-crash %>%
mutate(month = format(CRASH.DATE, "%m"), day = format(CRASH.DATE, "%d")) %>%
group_by(month, day) %>%count()
daily$date=seq(as.Date("2012-01-01"), as.Date("2012-12-31"),1)
ggplot(daily, aes(x=date, y=n)) +
  geom_line() + 
  xlab("")+scale_x_date(labels = date_format("%b"),limit=c(as.Date("2012-01-01"),as.Date("2012-12-31")))+
  labs(
    title = "Crashes based on day",
    x = "Days",
    y = "Number of crashes")
# Get the highest and lowest days
```

```{r}
bor<-crash%>% drop_na(BOROUGH)%>% group_by(BOROUGH)%>%count()
bor$BOROUGH<-str_to_title(bor$BOROUGH)
```

```{r}
bw<-crash%>%filter(BOROUGH =='BROOKLYN' | BOROUGH =='STATEN ISLAND')%>%group_by(BOROUGH,CRASH.TIME.hr.range)%>%count()
bw$n[bw$BOROUGH == 'BROOKLYN'] <- -bw$n
 ggplot(bw, aes(x = CRASH.TIME.hr.range, y = n, fill = BOROUGH)) + 
  geom_bar(data= subset(bw, BOROUGH == "BROOKLYN"), stat = "identity") + 
  geom_bar(data= subset(bw, BOROUGH == "STATEN ISLAND"), stat = "identity") + 
  scale_x_continuous(breaks = seq(23, 0, -1), labels=c("23" = "23-24", "22" = "22-23", "21" = "21-22", "20" = "20-21", "19" = "19-20", "18" = "18-19", "17" = "17-18", "16" = "16-17", "15" = "15-16", "14" = "14-15", "13" = "13-14", "12" = "12-13", "11" = "11-12", "10" = "10-11", "9" = "9-10", "8" = "8-9", "7" = "7-8", "6" = "6-7", "5" = "5-6", "4" = "4-5", "3" = "3-4", "1" = "1-2","2" = "2-3", '0' = "0-1"))+
  scale_y_continuous(breaks = seq(-40000, 40000, 10000), 
                     labels = paste0(as.character(c(4:0, 1:4)), "k")) + 
  coord_flip() + 
   labs(
    title = "Crashes comparison between Brooklyn and Staten Island",
    x = "Time in hours",
    y = "Number of crashes")+
  scale_fill_brewer(palette = "Set1") + 
  theme_bw()
```

```{r}
wzc<-crash%>%group_by(ZIP.CODE)%>%tally(sort=TRUE)%>%slice(1:10)
wzc
#Mention large number of missing values
```


```{r}
bb <- getbb("New York City, New York")
boundaries <- opq(bbox = bb) %>% 
  add_osm_feature(key = "boundary", value = "administrative") %>% 
  osmdata_sf() %>% 
  unname_osmdata_sf()

boroughs <- boundaries[["osm_multipolygons"]] %>% 
  filter(admin_level == 7)
b<-boroughs[c(3:7),]
b$name[b$name == "The Bronx"] <- "Bronx"
df<-merge(b, bor, by.x = "name",by.y='BOROUGH')
ggplot() +
  geom_sf(data = df, aes(fill = n))
```

```{r}
sd<-geojson_read('/Users/sarthakbhargava/Downloads/ZIP-CODES.geojson',what='sp')
wzc<-crash%>%group_by(ZIP.CODE)%>%tally()
wzc$ZIP.CODE<-as.character(wzc$ZIP.CODE)
spdf_fortified <- tidy(sd,region='postalCode')
spdf_fortified = spdf_fortified %>%
  left_join(. , wzc, by=c("id"="ZIP.CODE"))
spdf_fortified$n[is.na(spdf_fortified$n)] = 0.001
ggplot() +
  geom_polygon(data = spdf_fortified, aes(fill = n, x = long, y = lat, group = group)) +
  theme_void() +
  coord_map()
```


```{r}
crash$year<-format(crash$CRASH.DATE, "%Y")
yearly_2016<-crash%>%drop_na(ZIP.CODE)%>%filter(year<2017)%>%group_by(ZIP.CODE,year) %>%count()%>% 
  pivot_wider(names_from = year, 
              values_from = n)
yearly_2020<-crash%>%drop_na(ZIP.CODE)%>%filter(year>2016)%>%group_by(ZIP.CODE,year) %>%count()%>% 
  pivot_wider(names_from = year, 
              values_from = n)
yearly_2016<-yearly_2016 %>% mutate(mean_first = rowMeans(across(where(is.numeric)),na.rm=TRUE))%>%select(ZIP.CODE,mean_first)
yearly_2020<-yearly_2020 %>% mutate(mean_second = rowMeans(across(where(is.numeric)),na.rm=TRUE))%>%select(ZIP.CODE,mean_second)
yearly<-merge(x=yearly_2016,y=yearly_2020,by="ZIP.CODE")%>%mutate(diff=mean_second-mean_first)
yearly<-yearly[order(yearly$diff),]
yearly<-rbind(head(yearly,n=5),tail(yearly,n=5))
LtoM <-colorRampPalette(c('green', 'red' ))
Mid <- "snow3"
MtoH <-colorRampPalette(c('red', 'black'))
ggplot(data = yearly, aes(x = factor(ZIP.CODE), y = diff, 
              fill=diff)) +
       geom_bar(stat = 'identity') + 
       scale_fill_gradient2(low=LtoM(100), mid='snow3', 
       high=MtoH(100), space='Lab')+
  labs(
    title = "Most improved and deteriorated zip codes",
    x = "Zip codes",
    y = "Difference in crashes")
```







