# Conclusion

In this project we investigated the trend of accidents and the harm they cause across all the Boroughs of New York City. The analysis of 10 years of Motor Vehicle Crash Analysis data from 2012 to 2021 shows that the number of accidents increase and decrease in phases. The decrease could mean that the former years would have been more successful in implementing ways to curb accidents and the later has not. The reasons for this decrease need to be analyzed carefully and similar policies should be implemented state wide. On looking closer, we see that 2013 has a peak in the number of accidents and it slowly decreases since then upto the year 2015. Our investigation further shows that Brooklyn is the most unsafe in terms of road safety. This could be due to the fact that Brooklyn has a much higher population and population density (nearly 5 times the number of people per square mile). Brooklyn and Queens have the highest number of accdidents, people injured, and people killed in accidents across all of the Boroughs, whereas, Staten Island has the least in all of these respects. 

We also observed that the peak hours of the evening and afternoon from 2PM to 8PM see the most accidents. This makes sense since the highest number of cars on the road at these times. An unusual peak occurs at the time slot 12AM to 1AM. Since this is the time most public and recreational spots close, it is possible that the higher number of accidents are observed due to greater traffic. It is also noted that October sees the highest number of accidents. This could be due to the Halloween weekend which creates greater road traffic. Additionally, the change to shorter nights during this month causes visibility issues which could lead to more accidents. Further, the highest number of fatal crashes is observed during September. This could be caused by greater road traffic due to nicer weather, schools being back in session, and the Labor Day weekend. Days getting shorter may also be a contributing factor.
 
We also see that 29th Feb was naturally the day the fewest accidents were observed, which is logically accurate, as the date occurs once every 4 years. 

In terms of the contributing factors leading up to the accident, 'Unspecified' contributors have the highest occurance. It could involve a hit-and-run case or when the exact reason behind the accident could not be recorded. It is also clear that driver inattention/distraction and the failure to yield right-of-way are the two highest recorded causes of accidents. This often happens when the driver is under the influence or sleepy or the roads look mostly empty. 

Also, SUV's or Station wagons get into the highest number of accidents. Passenger vehicles and sedans form a close second and third respectively to SUV's or Station wagons. This could be because the most seen vehicles on the roads are also SUV's and passenger vehicles. 

One possible extension of our analysis in the future is to investigate connection between the weather conditions (temperature, rainfall) and the accidents in New York, since New York has drastic weather changes. Due to the limited time we could devote to this project, we were unable to explore that direction at this time.
